##  -*- python -*-  
# db file automatically generated by genconf on: Mon Jun 19 13:41:54 2023## insulates outside world against anything bad that could happen
## also prevents global scope pollution
def _fillCfgDb():
    from GaudiKernel.Proxy.ConfigurableDb import CfgDb

    # get a handle on the repository of Configurables
    cfgDb = CfgDb()

    # populate the repository with informations on Configurables 

    cfgDb.add( configurable = 'MuonFuzzStudyAlg',
               package = 'RockMuonCalibration',
               module  = 'RockMuonCalibration.RockMuonCalibrationConf',
               lib     = 'RockMuonCalibration' )
    cfgDb.add( configurable = 'PlexWriterAlg',
               package = 'RockMuonCalibration',
               module  = 'RockMuonCalibration.RockMuonCalibrationConf',
               lib     = 'RockMuonCalibration' )
    cfgDb.add( configurable = 'RockMuonCalibrationAlg',
               package = 'RockMuonCalibration',
               module  = 'RockMuonCalibration.RockMuonCalibrationConf',
               lib     = 'RockMuonCalibration' )
    return #_fillCfgDb
# fill cfgDb at module import...
try:
    _fillCfgDb()
    #house cleaning...
    del _fillCfgDb
except Exception,err:
    print "Py:ConfigurableDb   ERROR Problem with [%s] content!" % __name__
    print "Py:ConfigurableDb   ERROR",err
    print "Py:ConfigurableDb   ERROR   ==> culprit is package [RockMuonCalibration] !"
